on:
  push:
    branches:
      - main
jobs:
  # Build the documentation
  build:
    runs-on: windows-latest # Required by DocFX
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install DocFX
        run: choco install -y docfx
      - name: Use README.md as index.md
        run: cp README.md .documentation/index.md
      - name: Build
        run: docfx .documentation/docfx.json
      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: _site